[package]
name = "universal_liquidity_pool_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-client = { version = "0.31.0", features = ["async"] }
anchor-lang = "0.31.0"
thiserror = "2.0.12"
tokio = { version = "1.0", features = ["full"] }
